apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-elevate-blufountain-claims-admin-angular
  namespace: blufountain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blufountain-claims-admin-angular
  template:
    metadata:
      labels:
        app: blufountain-claims-admin-angular
    spec:
      containers:
      - name: blufountain-claims-admin-angular-container
        image: kaributechsworkflow/blufountain-self-service-web:5e76eab2e04348ae1d12ba612474ac3ad9edd736
        ports:
        ports:
        - containerPort: 4200
