apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-elevate-blufountain-claims-admin-angular
  namespace: blufountain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blufountain-claims-admin-angular
  template:
    metadata:
      labels:
        app: blufountain-claims-admin-angular
    spec:
      containers:
      - name: blufountain-claims-admin-angular-container
        image: kaributechsworkflow/blufountain-claims-admin-angular:f74ec3a2063d7f61ea5b623b5195e7d3f981a543
        imagePullPolicy: Always
        ports:
        - containerPort: 443
