apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-elevate-blufountain-claims-admin-angular
  namespace: blufountain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blufountain-claims-admin-angular
  template:
    metadata:
      labels:
        app: blufountain-claims-admin-angular
    spec:
      containers:
      - name: blufountain-claims-admin-angular-container
        image: kaributechsworkflow/blufountain-claims-admin-angular:edface69e244af63ce7c6d9cccf0b0234ff777e8
        imagePullPolicy: Always
        ports:
        - containerPort: 443
