user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    limit_req_zone $binary_remote_addr zone=app_rate_limit:10m rate=50r/m;

    # Redirect HTTP → HTTPS
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name localhost;

        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;
        server_name localhost;

        client_max_body_size 50M;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        ssl_session_timeout 1d;
        ssl_session_cache shared:ScaleliteSSL:10m;
        ssl_session_tickets off;
        ssl_protocols TLSv1.2 TLSv1.3;

        root /usr/share/nginx/html;
        index index.html;

        # Angular SPA routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Include any common directives
        include /etc/nginx/conf.d/nginx.common;
    }
}