import { ClaimDetail, ClaimListItem, ClaimsOverview } from '../models/claim.models';
import { DashboardData } from '../models/dashboard.models';

export const mockDashboardData: DashboardData = {
  stats: [
    { label: 'Total claims', value: '2,847', change: 'Up 12% from last month', tone: 'positive' },
    { label: 'Pending review', value: '186', change: 'Requires attention', tone: 'neutral', valueColor: '#EF9F27' },
    { label: 'Approved today', value: '43', change: 'Avg. $12,450', tone: 'neutral' },
    { label: 'Processing time', value: '3.2d', change: 'Down 0.5d improvement', tone: 'positive' },
    { label: 'Total payout MTD', value: '$1.8M', change: '234 claims paid', tone: 'neutral' },
    { label: 'Denial rate', value: '8.3%', change: 'Up 1.2% vs target', tone: 'negative' },
  ],
  volumeMetrics: [
    { label: 'Short-term disability', value: '986', width: '35%' },
    { label: 'Life insurance', value: '854', width: '30%', color: '#BA7517' },
    { label: 'Long-term disability', value: '427', width: '15%', color: '#D85A30' },
    { label: 'Accident insurance', value: '312', width: '11%', color: '#378ADD' },
    { label: 'Critical illness', value: '185', width: '7%', color: '#1D9E75' },
    { label: 'Hospital indemnity', value: '83', width: '3%', color: '#7F77DD' },
  ],
  footerStats: [
    { label: 'Avg claim value', value: '$45,320' },
    { label: 'Approval rate', value: '91.7%' },
    { label: 'Reopened', value: '23' },
  ],
  priorityItems: [
    { title: 'High value claims', detail: '12 claims > $100K', tone: 'high' },
    { title: 'Overdue reviews', detail: '8 claims > 5 days', tone: 'danger' },
    { title: 'Missing documents', detail: '27 awaiting info', tone: 'info' },
    { title: 'Fraud alerts', detail: '3 flagged for review', tone: 'success' },
  ],
};

export const mockClaimsOverview: ClaimsOverview = {
  totalClaims: '2,847',
  thisMonth: '312',
  thisWeek: '78',
  today: '12',
};

export const mockClaims: ClaimListItem[] = [
  {
    claimId: 'CLM-78492',
    initials: 'JM',
    avatarBackground: '#E6F1FB',
    avatarColor: '#378ADD',
    policyholder: 'Jennifer Martinez',
    policyNumber: 'POL-45892',
    type: 'Short-term',
    amount: '$8,500',
    filedDate: 'Mar 11, 2026',
    elapsed: '2 days ago',
    assigneeInitials: 'SK',
    assigneeBackground: '#EEEDFE',
    assigneeColor: '#534AB7',
    assigneeName: 'Sarah Kim',
    status: 'Pending',
    statusClass: 'status-pending',
    priority: 'HIGH',
    priorityClass: 'priority-high',
    actionLabel: 'Review',
  },
  {
    claimId: 'CLM-78491',
    initials: 'RC',
    avatarBackground: '#EEEDFE',
    avatarColor: '#534AB7',
    policyholder: 'Robert Chen',
    policyNumber: 'POL-33421',
    type: 'Life',
    amount: '$250,000',
    filedDate: 'Mar 10, 2026',
    elapsed: '3 days ago',
    assigneeInitials: 'DL',
    assigneeBackground: '#E1F5EE',
    assigneeColor: '#0F6E56',
    assigneeName: 'Dana Lee',
    status: 'Approved',
    statusClass: 'status-approved',
    priority: 'MED',
    priorityClass: 'priority-med',
    actionLabel: 'View',
  },
  {
    claimId: 'CLM-78490',
    initials: 'SA',
    avatarBackground: '#E1F5EE',
    avatarColor: '#0F6E56',
    policyholder: 'Sarah Anderson',
    policyNumber: 'POL-67234',
    type: 'Critical illness',
    amount: '$25,200',
    filedDate: 'Mar 10, 2026',
    elapsed: '3 days ago',
    assigneeInitials: 'SK',
    assigneeBackground: '#EEEDFE',
    assigneeColor: '#534AB7',
    assigneeName: 'Sarah Kim',
    status: 'Review',
    statusClass: 'status-review',
    priority: 'LOW',
    priorityClass: 'priority-low',
    actionLabel: 'Review',
  },
];

export const mockClaimDetails: Record<string, ClaimDetail> = {
  'CLM-78492': {
    claimId: 'CLM-78492',
    policyholder: 'Jennifer Martinez',
    policyNumber: 'POL-45892',
    insuranceType: 'Short-term Disability',
    claimAmount: '$8,500',
    dateFiled: 'March 11, 2026',
    status: 'Pending Review',
    statusClass: 'status-pending',
    priority: 'HIGH',
    priorityClass: 'priority-high',
    assigneeName: 'Sarah Kim',
    description:
      'Claimant is requesting short-term disability benefits due to a work-related back injury sustained on March 8, 2026. Medical documentation indicates a herniated disc requiring 6-8 weeks of recovery. Employee has been with the company for 4 years and is eligible for benefits under policy POL-45892.',
    documents: [
      'Medical Report - Dr. Anderson (March 9, 2026)',
      'Employer Incident Report (March 8, 2026)',
      'Claim Application Form',
      'W-2 Employment Verification',
    ],
    timeline: [
      { date: 'March 11, 2026 - 2:45 PM', user: 'Sarah Kim', description: 'assigned claim for review' },
      { date: 'March 11, 2026 - 10:22 AM', user: 'Jennifer Martinez', description: 'submitted the claim' },
      { date: 'March 9, 2026 - 3:15 PM', description: 'Medical documentation uploaded' },
      { date: 'March 8, 2026 - 11:00 AM', description: 'Incident reported to employer' },
    ],
  },
  'CLM-78491': {
    claimId: 'CLM-78491',
    policyholder: 'Robert Chen',
    policyNumber: 'POL-33421',
    insuranceType: 'Life Insurance',
    claimAmount: '$250,000',
    dateFiled: 'March 10, 2026',
    status: 'Approved',
    statusClass: 'status-approved',
    priority: 'MED',
    priorityClass: 'priority-med',
    assigneeName: 'Dana Lee',
    description:
      'Life claim approved after beneficiary verification, coverage validation, and payout review. Final documentation aligned with policy terms and beneficiary records.',
    documents: [
      'Certified Death Certificate',
      'Beneficiary Identification',
      'Policy Verification Summary',
      'Payout Approval Memo',
    ],
    timeline: [
      { date: 'March 12, 2026 - 4:20 PM', user: 'Dana Lee', description: 'approved the claim' },
      { date: 'March 11, 2026 - 1:40 PM', description: 'Beneficiary verification completed' },
      { date: 'March 10, 2026 - 9:05 AM', user: 'Robert Chen Estate', description: 'submitted the claim' },
    ],
  },
  'CLM-78490': {
    claimId: 'CLM-78490',
    policyholder: 'Sarah Anderson',
    policyNumber: 'POL-67234',
    insuranceType: 'Critical Illness',
    claimAmount: '$25,200',
    dateFiled: 'March 10, 2026',
    status: 'Under Review',
    statusClass: 'status-review',
    priority: 'LOW',
    priorityClass: 'priority-low',
    assigneeName: 'Sarah Kim',
    description:
      'Claim is being reviewed for diagnosis confirmation, waiting-period eligibility, and physician certification completeness before adjudication.',
    documents: [
      'Diagnosis Confirmation Letter',
      'Attending Physician Statement',
      'Claimant Identification',
    ],
    timeline: [
      { date: 'March 12, 2026 - 10:10 AM', user: 'Sarah Kim', description: 'requested supplemental physician notes' },
      { date: 'March 10, 2026 - 8:15 AM', user: 'Sarah Anderson', description: 'submitted the claim' },
    ],
  },
};
