apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-claims-admin-angular
  namespace: blufountain-insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blufountain-claims-admin-angular
  template:
    metadata:
      labels:
        app: blufountain-claims-admin-angular
        appVersion: 'b535ee1a4bccae173105fff0543aca0bbffade82'
    spec:
      containers:
      - name: blufountain-claims-admin-angular-container
        image: kaributechsworkflow/blufountain-claims-admin-angular:dcb0e72f78b02e3c953e5aa126912d20e33d25c6
        ports:
        - containerPort: 443
