apiVersion: apps/v1
kind: Deployment
metadata:
  name: blufountain-claims-admin-angular
  namespace: blufountain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blufountain-claims-admin-angular
  template:
    metadata:
      labels:
        app: blufountain-claims-admin-angular
        appVersion: 'b535ee1a4bccae173105fff0543aca0bbffade82'
    spec:
      containers:
      - name: blufountain-claims-admin-angular-container
        image: kaributechsworkflow/blufountain-claims-admin-angular:91ee82f43690a385bab2fbd56b7722ac1a8fde3c
        ports:
        - containerPort: 443
